nosana:
  description: "Template Repo Pipeline"
  

global:
  image: alpine:latest

  trigger:
    branch:
      - main

jobs:
  - name: "Install Dependencies"
    commands:
      - ls -lah
      - env
      - cwd